{"uuid":"73213a3c-c8aa-4035-ad53-d51f497e21b8","historyId":"8b1db0ed0707de62e1d6af48974b0243","fullName":"ResetPasswordTest.testCodeSubmission","labels":[{"name":"package","value":"ResetPasswordTest"},{"name":"testClass","value":"ResetPasswordTest"},{"name":"testMethod","value":"testCodeSubmission"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"iZDE"},{"name":"subSuite","value":"ResetPasswordTest"},{"name":"host","value":"OniGiri"},{"name":"thread","value":"4864@OniGiri.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"testCodeSubmission","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Неожиданное сообщение об ошибке: Неправильный код. Попробуйте снова. expected [true] but found [false]","trace":"java.lang.AssertionError: Неожиданное сообщение об ошибке: Неправильный код. Попробуйте снова. expected [true] but found [false]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1578)\r\n\tat org.testng.Assert.assertTrue(Assert.java:57)\r\n\tat ResetPasswordTest.testCodeSubmission(ResetPasswordTest.java:110)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:819)\r\n\tat org.testng.TestRunner.run(TestRunner.java:619)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:336)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1228)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1134)\r\n\tat org.testng.TestNG.run(TestNG.java:1101)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","steps":[{"name":"Пробуем код: 00000","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1734690094614,"stop":1734690094614},{"name":"Код 00000 не подошёл","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1734690099737,"stop":1734690099737}],"attachments":[],"parameters":[],"start":1734690093526,"stop":1734690099862}